<a href="https://colab.research.google.com/github/LukasEder1/CKE-Datasets/blob/main/Demo/InspectDatasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone "https://github.com/LukasEder1/CKE-Datasets.git"

Cloning into 'CKE-Datasets'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 21 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (21/21), 818.33 KiB | 1.29 MiB/s, done.

In [2]:
import pandas as pd

In [5]:
policies = pd.read_csv("/content/CKE-Datasets/policies.csv")
articles = pd.read_csv("/content/CKE-Datasets/articles.csv")

# Princeton-Leuven Longitudinal Corpus of Privacy Policies

In [7]:
policies.head(10)

,Id,Keywords,TextA,TextB,LengthA,LengthB,LengthDifference,YearA,YearB,YearsApart
0,90536,"['European Union', 'cookies', 'bugs', 'persona...",## This Privacy Policy is effective as of Sept...,## This Privacy Policy is effective as of Marc...,10104,14003,3899,2008,2012,4
1,90344,"['Telerik', 'May', 'Progress Software', 'softw...","Last update: Tuesday, November 15, 2011\n\nWe ...",Please note this governs the use of the Progre...,16703,24200,7497,2013,2016,3
2,98640,"['validation page', 'scripts', 'removing HTML5...",Effective Date: 08/07/2014 \nPosting Date: 08...,Effective Date: 01/15/2016 \nPosting Date: 01...,25152,24484,-668,2015,2016,1
3,98585,"['account settings', 'center cloud', 'cloud co...",## Kaspersky Lab Privacy Policy for Websites\n...,## Kaspersky Lab Privacy Policy for Websites\n...,44999,49700,4701,2018,2019,1
4,99880,"['reproductive science', 'science center', 'Mi...",This document describes how information about ...,## \nPrivacy Policy \n\n\nThis notice descr...,9239,9617,378,2009,2017,8
5,108079,"['destination nsw', 'Insights', 'Viva Sydney',...",Tourism New South Wales is committed to mainta...,Destination NSW is committed to maintaining yo...,11502,10554,-948,2008,2012,4
6,90555,"['serve ads', 'DART cookie', 'registration num...",Property Abroad is committed to protecting you...,## Our Privacy Policy\n\nProperty-Abroad.com ...,1805,2669,864,2004,2016,12
7,90545,"['Yahoo privacy', 'Privacy Policy', 'AOL', 'Oa...",### How to Opt-Out\n\nYou can opt-out of targe...,"Oath, part of the Verizon family of companies,...",1638,3845,2207,2016,2017,1
8,98553,"['customeraffiliated websites', 'providers', '...","Last Updated: November 10, 2010\n\nThis Privac...","Last Updated: April 20, 2016\n\nThis Privacy P...",13201,11496,-1705,2015,2017,2
9,98572,"['job applications', 'Privacy Shield', 'Shield...",Effective Date: 7/25/2014\n\nThis privacy poli...,Effective Date: 9/26/2016\n\n * This privacy ...,14704,17120,2416,2015,2016,1

In [9]:
policies.iloc[0].Keywords

"['European Union', 'cookies', 'bugs', 'personally identifiable', 'Salesforce', 'identifiable information', 'customer testimonial', 'version', 'Third Party', 'clear gifs', 'web beacons', 'service providers', 'blog']"

# News Edits: News Article Revision

In [8]:
articles.head(10)

,Id,Keywords,TextA,TextB,LengthA,LengthB,LengthDifference,VersionA,VersionB,Magazine
0,16532,"['Toys R', 'R us', 'toy makers', 'Hong Kong', ...",NEW YORK (AP) -- Toys R Us is headed toward s...,NEW YORK (AP) -- The demise of Toys R Us will...,5765,6971,1206,0.0,4.0,Associated Press
1,7335,"['nuclear weapons', 'united states', 'north ko...","SEOUL, South Korea (AP) -- South Korean media...","SEOUL, South Korea (AP) -- New South Korean P...",863,3796,2933,0.0,3.0,Associated Press
2,16625,"['50 million', 'million users', 'trump campaig...","Facebook suspended Cambridge Analytica, a data...",WASHINGTON (AP) -- A data analysis firm emplo...,3824,5779,1955,0.0,8.0,Associated Press
3,3694,"['filmmaker Jason', 'Jason Pollock', 'departme...","CLAYTON, Mo.\n(AP) -- St. Louis County prosec...","FERGUSON, Mo.\n(AP) -- A prosecutor was criti...",4604,5426,822,0.0,2.0,Associated Press
4,7409,"['Puerto ricans', 'statehood', 'lost loved', '...","SAN JUAN, Puerto Rico (AP) -- Puerto Rico nat...","SAN JUAN, Puerto Rico (AP) -- Puerto Rico nat...",4394,6332,1938,0.0,2.0,Associated Press
5,1525,"['white house', 'TRUMP ADMINISTRATION', 'pales...","RAMALLAH, West Bank (AP) -- Palestinian leade...","RAMALLAH, West Bank (AP) -- Palestinian Presi...",6556,6277,-279,0.0,3.0,Associated Press
6,16699,"['prime minister', 'foreign leaders', 'bilater...",MOSCOW (AP) -- U.S.\nPresident Donald Trump c...,MOSCOW (AP) -- U.S.\nPresident Donald Trump c...,1939,2661,722,0.0,5.0,Associated Press
7,8370,"['removed 92', '92 million', 'million videos',...",DETROIT (AP) -- In the wake of Britain's thir...,DETROIT (AP) -- In the wake of Britain's thir...,5140,6144,1004,0.0,2.0,Associated Press
8,15397,"['31, 2018', 'united states', 'Quarterly progr...",WASHINGTON (AP) -- The railroad industry is d...,WASHINGTON (AP) -- The railroad industry is p...,4896,4805,-91,0.0,6.0,Associated Press
9,17354,"['Researcher Autumn', 'Autumn Stroup', 'city r...","ANCHORAGE, Alaska (AP) -- Voters in Alaska's ...","ANCHORAGE, Alaska (AP) -- Voters in Alaska's ...",5038,5612,574,0.0,5.0,Associated Press

In [11]:
articles.iloc[1].Keywords

"['nuclear weapons', 'united states', 'north korea', 'Yoon said', 'Park Geun-hye', 'missile provocation', 'last week', 'Hwasong-12 missile']"